---
ckan_package_filename: 'python-ckan_{{ ckan_version }}-trusty_amd64.deb'

# The config and virtualenv are installed by the CKAN package
ckan_config_path: "/etc/ckan/default/production.ini"
ckan_virtualenv_path: "/usr/lib/ckan/default/"

ckan_pip_dependencies:
  - { name: 'setuptools', version: '40.0.0'}
  - { name: 'wheel', version: '0.31.1'}
  - { name: 'urllib3[secure]', version: '1.19.1' }
  - { name: 'requests[security]', version: '2.10.0' }

ckan_simple_plugins:
  - name: 'ckanext-pages'
    repo: 'ckan/ckanext-pages'
    version: '8b0d555027f1d4ab47291da57a806e617343a6c0'
    plugins:
      - 'pages'
  - name: 'ckanext-showcase'
    repo: 'azavea/ckanext-showcase'
    version: 'ba15d2dc586faf788ffead76b1595ff82cdda7a9'
    plugins:
      - 'showcase'
