---
ckan_package_filename: 'python-ckan_{{ ckan_version }}-trusty_amd64.deb'

# The config and virtualenv are installed by the CKAN package
ckan_config_path: "/etc/ckan/default/production.ini"
ckan_virtualenv_path: "/usr/lib/ckan/default/"

ckan_pip_dependencies:
  - { name: 'setuptools', version: '40.0.0'}
  - { name: 'wheel', version: '0.31.1'}
  - { name: 'urllib3[secure]', version: '1.19.1' }
  - { name: 'requests[security]', version: '2.10.0' }

ckan_simple_plugins:
  - name: 'ckanext-showcase'
    repo: 'ckan/ckanext-showcase'
    version: '87a7a6e1d3566edae615613f705b3b83bef75281'
    plugins:
      - 'showcase'
